### ISSUE TITLE
3D touch crashing on iPhone 7

### ISSUE THREAD

**Issue by drehren** [Nyx0uf/MPDRemote#9] opened 2017-04-22 23:15 UTC
When doing 3D touch on an Album or Playlist the app crashes.

**Comment by Nyx0uf** [comment] 2017-04-24 06:57
Does it always happen ? I don't have a force-touch capable device and I can't reproduce it in the simulator

**Comment by drehren** [comment] 2017-04-24 12:54
It's working now in Albums, but I've found that is failing in the others... it happens after I visit the Playlist page, if I don't the app doesn't crash in neither Artists or Genres.
It always crashes in the Playlist page.

**Comment by Nyx0uf** [comment] 2017-04-24 12:56
For info : It's only implemented for Albums and Playlists

**Comment by Nyx0uf** [comment] 2017-04-24 16:49
OK I found the problem

**Comment by Nyx0uf** [comment] 2017-05-03 20:00
fixed in 1.11

**Closed by Nyx0uf** 2017-05-03 20:00 UTC
Labels: bug
